# Generated by Django 3.0.5 on 2020-04-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazondotcom',
            name='price',
            field=models.CharField(max_length=20),
        ),
    ]
